// "use client"

import { Inter } from "next/font/google";
import "./globals.css";
import { ThirdwebProvider } from "./thirdweb";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import NavBar from "../components/NavBar";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Crowdfunding dapp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdwebProvider>
          <NavBar/>
          {children}
          <ToastContainer autoClose={1700} />
          </ThirdwebProvider>
        
        </body>
    </html>
  );
}
